// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvznpxysjjfepihtyrwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2em5weHlzampmZXBpaHR5cnd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5ODQ4MzcsImV4cCI6MjA3MTU2MDgzN30.WjuSMUQgpZRCCPxqH42vO6-ViKYarC8jAz02lqzgwR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});